chart/apisix/templates/NOTES.txt
=> chore: fix the service name in NOTES.txt

charts/apisix-ingress-controller/.helmignore, charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml, charts/apisix-ingress-controller/templates/NOTES.txt, charts/apisix-ingress-controller/templates/_helpers.tpl, charts/apisix-ingress-controller/templates/configmap.yaml, charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix-ingress-controller/templates/hpa.yaml, charts/apisix-ingress-controller/templates/rbac.yaml, charts/apisix-ingress-controller/templates/service-account.yaml, charts/apisix-ingress-controller/templates/service.yaml, charts/apisix-ingress-controller/values.yaml
related: https://github.com/apache/apisix-ingress-controller/issues/256
=> feat: add ingress controller helm chart

charts/apisix/templates/deployment.yaml, charts/apisix/values.yaml
@tokers @gxthrj 
https://github.com/apache/apisix-helm-chart/pull/26 no update for a long time, I recreate PR to fix https://github.com/apache/apisix-helm-chart/issues/28
=> fix: break change with affinity

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/values.yaml, charts/apisix/Chart.yaml, charts/apisix/values.yaml
- apisix-ingress-controller upgrade to 0.3.0 / helm chart 0.2.0
- apisix upgrade to 2.3.0 / helm chart 0.2.0
@tokers
=> feat: upgrade dependency

docs/en/latest/apisix-ingress-controller.md, docs/en/latest/config.json
https://github.com/apache/apisix-website/issues/298
=> fix: for helm chart and docker ,tell users where they are

docs/en/latest/apisix-dashboard.md, docs/en/latest/apisix-ingress-controller.md, docs/en/latest/apisix.md
=> fix: duplicate titles appear in the website #56

charts/apisix-dashboard/Chart.yaml, charts/apisix-dashboard/templates/configmap.yaml, charts/apisix-dashboard/templates/deployment.yaml, charts/apisix-dashboard/templates/hpa.yaml, charts/apisix-dashboard/templates/ingress.yaml, charts/apisix-dashboard/templates/service.yaml, charts/apisix-dashboard/templates/serviceaccount.yaml
```
$ helm install --debug --name apisix-dashboard . --namespace edge --dry-run > /tmp/apisix-dashboard.sh
```
=> feat: add namespace support for apisix-dashboard when using helm

charts/apisix-dashboard/Chart.yaml, charts/apisix/Chart.yaml
the apisix/values.yaml properties dashboard.enabled and ingress-controller.enabled doesn't work, so update the chart version of dashboard and ingress-controller.
=> fix: update the chart version of dashboard and ingress-controller

charts/apisix-ingress-controller/README.md
=> add README for charts/apisix-ingress-controller

charts/apisix-ingress-controller/templates/service-account.yaml, charts/apisix-ingress-controller/values.yaml
improve Helm chart
xref: https://github.com/apache/apisix-helm-chart/issues/70
=> feat: add ability to specify automountServiceAccountToken

charts/apisix/Chart.yaml
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
Bump apisix chart version to 0.3.3.
=> chore: apisix chart 0.3.3

charts/apisix-ingress-controller/Chart.yaml
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
=> chore: ingress controller chart version 0.4.1

charts/apisix-ingress-controller/templates/rbac.yaml
fixes #78 
fix RBAC permissions according to https://github.com/apache/apisix-ingress-controller/pull/452
=> chore: fix RBAC permissions

docs/en/latest/apisix.md
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
=> doc: fix ingress controller admin.allow.ipList

.github/workflows/ci.yaml, .gitmodules, charts/apisix-dashboard/Chart.yaml, charts/apisix-ingress-controller/Chart.yaml, charts/apisix/Chart.yaml, charts/apisix/values.yaml, test/e2e/kind.yaml
=> chore: add ci

charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml, charts/apisix-ingress-controller/templates/rbac.yaml
Signed-off-by: Ling Samuel <lingsamuelgrace@gmail.com>
Fixes #85
=> fix: events, ingress status permission; add subresource

charts/apisix-ingress-controller/templates/_helpers.tpl, charts/apisix-ingress-controller/templates/servicemonitor.yaml, charts/apisix-ingress-controller/values.yaml
=> feat: add service monitor

charts/apisix/README.md, charts/apisix/templates/service-gateway.yaml, charts/apisix/values.yaml
=> chore: add externalTrafficPolicy for apisix gateway service

docs/en/latest/apisix-dashboard.md, docs/en/latest/apisix.md
=> docs: fix install docs

charts/apisix-dashboard/Chart.yaml
=> fix: apisix-dashboard appversion mismatch real version

charts/apisix/templates/configmap.yaml
=> chore: If ingress-controller is enabled, allow it automatically

charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml
=> chore: sync CRDs

charts/apisix-ingress-controller/templates/rbac.yaml
=> chore: fix RBAC

.github/workflows/release.yaml, .gitmodules
=> ci: add ci for release helm chart

.github/workflows/release.yaml
=> chore: fix helm release branch name

.asf.yaml
=> chore: enable pages for host helm chart

docs/en/latest/FAQ.md
fix : [471](https://github.com/apache/apisix-website/issues/471)
=> fix: typo errors in helm-chart FAQ page

charts/apisix/Chart.yaml
Update chart version to release recent changes
> * feat: support etcd config for apisix helm chart (#169)
> * feat: apisix.podAnnotations invalid param (#168)
> * feat: support ssl_trusted_certificate for apisix helm chart (#166)
> * feat: apisix chart support custom configuration snippet (#165)
=> chore: update apisix chart version to 0.7.2

charts/apisix/README.md, charts/apisix/templates/_helpers.tpl, charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
link: [Integration service discovery registry](https://apisix.apache.org/docs/apisix/discovery)
=> feat: add service discovery

charts/apisix/templates/service-gateway.yaml, charts/apisix/values.yaml
Fix for issue #184 to use the correct condition
=> Fix condition to use gateway.externalIPs

charts/apisix/templates/configmap.yaml, charts/apisix/templates/deployment.yaml, charts/apisix/templates/servicemonitor.yaml, charts/apisix/values.yaml
=> feat(apisix): add service monitor support

charts/apisix-dashboard/README.md
resolve #189 
Add README.md for apisix-dashboard chart
=> docs: add README.md for apisix-dashboard

charts/apisix/README.md
=> docs: add service monitor parameters doc

charts/apisix/README.md
update labels description #194
=> docs: update service monitor labels description

charts/apisix/Chart.yaml
ref: https://github.com/apache/apisix-helm-chart/issues/186#issuecomment-1002888696
Recently we have added some features, I think it is worth to make a new relase so that these features can be used by users.
e.g.
* service monitor
* access log and error log
* service discovery
* ...
Full diff can see here: https://github.com/apache/apisix-helm-chart/compare/apisix-0.7.2...master
=> chore: make a new release

charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
ref: https://github.com/apache/apisix/pull/5960
=> feat(metrics): Add the param - metricPrefix

charts/apisix-dashboard/README.md, charts/apisix-dashboard/templates/configmap.yaml, charts/apisix-dashboard/values.yaml
[Refer to Dashboard Configuration](https://github.com/apache/apisix-dashboard/blob/1fa139f5316805f6f2ae765434ab47615256bc3d/api/conf/conf.yaml#L48)
=> feat(apisix-dashboard): add etcd prefix

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml, charts/apisix-ingress-controller/templates/configmap.yaml, charts/apisix-ingress-controller/templates/rbac.yaml, charts/apisix-ingress-controller/values.yaml
=> chore: apisix-ingress v1.4

charts/apisix/templates/deployment.yaml, charts/apisix/templates/service-gateway.yaml
=> feat(apisix): expose stream proxy tcp/udp ports

charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix-ingress-controller/values.yaml
Add pod annotations to the APISIX ingress controller deployment.
=> feat: add podAnnotations to apisix-ingress-controller

.gitignore, charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/templates/deployment.yaml, charts/apisix/values.yaml
Signed-off-by: 赵安家 <anjia0532@gmail.com>
1. extraVolumes: []
2. extraVolumeMounts: []
=> feat: apisix add extraVolumeMounts and extraVolume

charts/apisix-ingress-controller/templates/configmap.yaml, charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix-ingress-controller/templates/hpa.yaml, charts/apisix-ingress-controller/templates/service-account.yaml, charts/apisix-ingress-controller/templates/service.yaml
Signed-off-by: Wei Jiang <machowei01@gmail.com>
Solved Issue: #273
=> chore: Add namespace for apisix-ingress-controller

charts/apisix-dashboard/Chart.yaml, charts/apisix-dashboard/values.yaml
Related issue: https://github.com/apache/apisix-helm-chart/issues/267
=> feat: upgrade APISIX dashboard to 2.11.0

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/values.yaml
=> chore: upgrade apisix-ingress-controller to 1.4.1

charts/apisix-ingress-controller/values.yaml
fixes: https://github.com/apache/apisix-ingress-controller/issues/1003
=> fix: update default ApisixRoute version to v2beta3

charts/apisix-ingress-controller/Chart.yaml
=> chore: bump APISIX Ingress chart version

charts/apisix/README.md
Added docs as requested in the linked ticket
=> #294: added initContainer override parameter docs

charts/apisix/Chart.yaml, charts/apisix/values.yaml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> feat: upgrade APISIX to 2.14.1

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml
fixes https://github.com/apache/apisix-ingress-controller/issues/1092
=> fix: make ApisixRouteHTTPBackend support serivce name

charts/apisix/templates/configmap.yaml
xref: https://github.com/apache/apisix-helm-chart/pull/310#discussion_r911641138
/cc @fengxsong @spacewander
=> chore: revert access_log_format quote

charts/apisix/README.md, charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
=> chore: support configuring SSL protocols

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/values.yaml
=> chore: APISIX Ingress v1.5.0

charts/apisix-ingress-controller/Chart.yaml
=> chore: mark APISIX Ingress as release version

index.yaml
=> chore: refresh cache

charts/apisix/README.md, charts/apisix/values.yaml
Signed-off-by: 117503445 <t117503445@gmail.com>
=> docs: fix apisix chart readme (#367)

docs/en/latest/FAQ.md
Added a new FAQ on _How to install Apache APISIX running in standalone mode._
Screenshot of the Yaml file display:
=> docs: How to install Apache APISIX running in standalone mode?

charts/apisix-ingress-controller/templates/rbac.yaml
=> fix: extensions API Group RBAC

charts/apisix-dashboard/templates/deployment.yaml, charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix/templates/_pod.tpl
=> fix: podAnnotations render error

charts/apisix/Chart.yaml, charts/apisix/values.yaml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> feat: upgrade APISIX to 2.15.1

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/crds/customresourcedefinitions.yaml, charts/apisix-ingress-controller/templates/configmap.yaml, charts/apisix-ingress-controller/values.yaml
https://github.com/apache/apisix-ingress-controller/releases/tag/1.6.0-rc1
=> chore: release APISIX Ingress controller v1.6.0-rc1

charts/apisix-dashboard/Chart.yaml, charts/apisix-dashboard/values.yaml
Signed-off-by: Gallardot <tttick@163.com>
=> feat: upgrade APISIX-Dashboard to 2.15.0

charts/apisix-dashboard/README.md, charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml, docs/en/latest/apisix.md
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> feat: upgrade APISIX to 3.0.0

charts/apisix-dashboard/README.md, charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/templates/configmap.yaml
=> fix: Bad configuration items cause incompatible Ingress and apisix

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/templates/configmap.yaml, charts/apisix-ingress-controller/values.yaml
=> fix: move item to keep it consistent

charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> chore: upgrade APISIX to 3.1.0

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/values.yaml
=> chore: APISIX Ingress v1.6.0 release

.asf.yaml, .github/workflows/release.yaml
follow https://github.com/apache/apisix-helm-chart/issues/419
I will create legacy branch
Update and publish the Helm chart of APISIX v2 on this branch
=> chore: add legacy branch

.github/workflows/release.yaml
=> ci: enable legacy release

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/templates/configmap.yaml, charts/apisix/templates/service-control-plane.yaml, charts/apisix/values.yaml
=> feat: add decoupled mode support

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
=> feat: add certs for decoupled-mode

charts/apisix/templates/service-gateway.yaml
=> fix: add prometheus port for apisix-gateway

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/templates/configmap.yaml, charts/apisix/values.schema.json, charts/apisix/values.yaml
=> feat: add valid for plugins

charts/apisix-ingress-controller/Chart.yaml
Sync some modifications to the new version.
=> chore: bump Ingress chart version to 0.11.4

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
fixes: https://github.com/apache/apisix-helm-chart/issues/476
=> feat: support configuring APISIX admin_key via secret

charts/apisix/templates/configmap.yaml
=> fix:service discovery minimal Kubernetes

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/values.yaml
=> feat: Customize the readiness probe of APISIX pod (#545)

charts/apisix-ingress-controller/templates/deployment.yaml
As per the proposal in https://github.com/apache/apisix-helm-chart/issues/563
=> feat: add security context for ingress container

.github/workflows/ci.yaml
issue:
https://github.com/apache/apisix-helm-chart/issues/438#issue-1517120651
=> refractor(helm-docs task):to make it execute only once

charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml
https://github.com/apache/apisix-helm-chart/pull/576#issuecomment-1627988833
=> chore(dev): upgrade APISIX to 3.4.0

charts/apisix-dashboard/Chart.yaml
Trigger release of new chart version to obtain latest chart features like hpa versions support
=> chore: release apisix dashboard v0.8.1

charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/templates/servicemonitor.yaml, charts/apisix-ingress-controller/values.yaml, charts/apisix/README.md, charts/apisix/templates/service-monitor.yaml, charts/apisix/values.yaml
=> feat: support adding metrics relabeling config

charts/apisix-dashboard/README.md, charts/apisix-dashboard/templates/deployment.yaml, charts/apisix-dashboard/values.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix-ingress-controller/values.yaml, charts/apisix/README.md, charts/apisix/values.yaml
As per https://github.com/apache/apisix-helm-chart/issues/582
=> feat: add updateStrategy settings for ingress and dashboard

charts/apisix/templates/_pod.tpl
As per https://github.com/apache/apisix-helm-chart/issues/586
=> feat: allow to use tpl for apisix pod annotations

charts/apisix/templates/configmap.yaml
=> fix: configmap admin/viewer secret key format

charts/apisix-ingress-controller/templates/servicemonitor.yaml, charts/apisix/templates/service-monitor.yaml
As per https://github.com/apache/apisix-helm-chart/issues/614
=> fix: fix templating of the metricRelabelings parameter

charts/apisix-ingress-controller/Chart.yaml
Release a new version with a bugfix for https://github.com/apache/apisix-helm-chart/issues/614
@tao12345666333, @Gallardot, @AlinsRan please review
=> chore: release ingress v0.12.1

charts/apisix/README.md, charts/apisix/templates/configmap.yaml, charts/apisix/values.yaml
=> feat: allow configuring data_encryption keys

charts/apisix/README.md, charts/apisix/templates/_pod.tpl, charts/apisix/values.yaml
see (https://github.com/apache/apisix-helm-chart/issues/626)
=> Adds security context for init containers 

charts/apisix/README.md, charts/apisix/values.yaml
=> bugfix: metricRelabelings default value

charts/apisix-ingress-controller/templates/apisix-configmap.yaml, charts/apisix-ingress-controller/templates/deployment.yaml
Enable prometheus plugins for service monitoring
=> feat: Enable prometheus plugins for ingress's composite mode service monitoring

charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/templates/apisix-configmap.yaml, charts/apisix-ingress-controller/templates/service-apisix.yaml, charts/apisix-ingress-controller/values.yaml
Adding nginx configuration & gateway type in composite architecture
=> feat: adding nginx configuration & gateway type in composite architecture 

charts/apisix/templates/configmap.yaml
refer: https://github.com/apache/apisix-helm-chart/pull/658
=> fix: delete the condition of deployment role

charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml
https://github.com/apache/apisix/blob/release/3.8/CHANGELOG.md#380
=> chore: upgrade APISIX to 3.8.0

charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml
https://github.com/apache/apisix/blob/release/3.8/CHANGELOG.md#380
=> chore(dev): upgrade APISIX to 3.8.0

charts/apisix-ingress-controller/templates/ingress-class.yaml
Fixes https://github.com/apache/apisix-ingress-controller/issues/2133
=> fix: allow configuring apiVersion in Ingress Class resource

charts/apisix-dashboard/Chart.yaml
Release of a new version 0.8.2 of the dashboard chart. Includes:
- https://github.com/apache/apisix-helm-chart/pull/651
=> chore: release dashboard 0.8.2

charts/apisix/Chart.yaml, charts/apisix/templates/_helpers.tpl
This PR fixes problem with incorrect mapping of admin credentials to update values file
=> fix: fix path to values of admin credentials in helpers

charts/apisix/Chart.yaml, charts/apisix/README.md, charts/apisix/values.yaml
https://github.com/apache/apisix/blob/release/3.11/CHANGELOG.md#3110
=> chore: upgrade APISIX to 3.11.0

charts/apisix-ingress-controller/Chart.yaml, charts/apisix-ingress-controller/README.md, charts/apisix-ingress-controller/templates/deployment.yaml, charts/apisix-ingress-controller/values.yaml
https://lists.apache.org/thread/777qoftwg0z8zsfx3f3067c40wnvh0w2
release 2.0.0-rc4
=> feat: release ingress 2.0.0-rc4
