- .asf.yaml
Fix: 
An error occurred while running github feature in .asf.yaml
.asf.yaml: Invalid GitHub label 'helm chart' - must be lowercase alphanumerical and <= 35 characters
> fix: asf labels

- README.md
- chart/apisix/templates/configmap.yaml
- chart/apisix/templates/deployment.yaml
- chart/apisix/values.yaml
1. Suports add multiple etcdhost.
2. `etcd.port` has modified to `etcd.default`.
3. Modifiy README.me.
4. Add default anti-affinity to deployment.yaml template, default false. turn on anti-affinity by `--set affinity.enabled=true`
> Modify Helm template to support multiple etcdhost, add anti-affinity

- charts/apisix/Chart.yaml
- charts/apisix/templates/configmap.yaml
- charts/apisix/templates/deployment.yaml
- charts/apisix/values.yaml
`gateway.k8s_domain` and `etcd.defaultPort` is invalid for etcd, 
use `etcd.clusterDomain` and `etcd.service.port` instead them.
> chore: remove invalid values

- charts/apisix/Chart.yaml
- charts/apisix/values.yaml
add dashboard and ingress-controller as component of apisix.
We can deploy `apisix`, `apisix-dashboard` and `apisix-ingress-controller` together.
`helm install apisix --set dashboard.enabled=true --set ingressController.enabled=true`
```
apisix-etcd-0                                1/1     Running   0          22m
apisix-dashboard-94f89d48-r79sf              1/1     Running   3          22m
apisix-d9744dc9f-fg47x                       1/1     Running   0          22m
apisix-ingress-controller-5cf7cc8bbc-wm2wx   1/1     Running   0          3m5s
```
> feat: add dashboard and ingress-controller as component of apisix

- .gitignore
- charts/apisix-dashboard/Chart.yaml
- charts/apisix/Chart.yaml
- charts/apisix/templates/ingress.yaml
fix dashboard ingress apiVersion when kubernetes version in v14 newline bug,
add apisix gateway ingress suppurt, just in default values.yaml, not any ingress defined.
> fix: dashboard ingress and apisix gateway ingress

- charts/apisix/Chart.yaml
- charts/apisix/values.yaml
before: 
`helm install apisix apisix/apisix --set ingressController.enabled=true --set ingress-controller.replicaCount=2`
after:
`helm install apisix apisix/apisix --set ingress-controller.enabled=true --set ingress-controller.replicaCount=2`
> fix: unified subchart value name

- charts/apisix/Chart.yaml
- charts/apisix/values.yaml
Apache APISIX 2.5 had been released several days ago, it's time to update the charts.
> chore: use apisix:2.5-apline image

- README.md
Since this PR (https://github.com/apache/apisix-helm-chart/pull/47) has moved the installation documentation of each item to the `docs/en/latest` directory, but the link in the README.md document has not been modified. Therefore, this PR mainly links each item in the README.md document to the corresponding installation document.
> docs: fix the README.md doc link

- charts/apisix/values.yaml
Add new top-level `apisix.enabled` setting to control whether
deploy apisix-ingress controller only.
> feat: support for controller-only deployment

- charts/apisix-dashboard/Chart.yaml
- charts/apisix-dashboard/values.yaml
Currently, the default installation version of APISIX is `2.5`, but the default installation version of apisix-dashboard is `2.3`, and the versions between them are not compatible. This PR is to update the default installed version of apisix-dashboard to 2.6, which solves the problem of incompatible versions when apisix-dashboard and apisix are installed by default.
https://github.com/apache/apisix-helm-chart/blob/c7edd2da0bac6a1c350478226cbee3c20a9556bc/charts/apisix/values.yaml#L22
https://github.com/apache/apisix-helm-chart/blob/c7edd2da0bac6a1c350478226cbee3c20a9556bc/charts/apisix-dashboard/values.yaml#L27
> chore: update the default version of apisix-dashboard

- charts/apisix-ingress-controller/Chart.yaml
- charts/apisix-ingress-controller/values.yaml
APISIX Ingress controller v0.6.0 has been released 22 days ago.
full diff https://github.com/apache/apisix-ingress-controller/compare/0.5.0...0.6.0
> chore: bump apisix-ingress-controller to v0.6.0

- docs/en/latest/FAQ.md
- docs/en/latest/apisix.md
- docs/en/latest/config.json
fix : [#426](https://github.com/apache/apisix-website/issues/426)
Currently[ FAQ selection ](https://apisix.apache.org/)contains only APISIX,APISIX Dashboard and APISIX IngressController.
I think We could add Helm Chart FAQ to sidebar and add that in navbar FAQ selection of  Apisix website  too.
> feat: add helm chart FAQ entry on the navbar

- charts/apisix/templates/configmap.yaml
Trailing white space lead ConfigMap can't format properly. Like this:
> fix: remove trailing white space in configmap

- charts/apisix-ingress-controller/templates/servicemonitor.yaml
- charts/apisix-ingress-controller/values.yaml
If [serviceMonitorSelector.matchLabels](https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/user-guides/getting-started.md#include-servicemonitors) are enabled, we need some extra labels for service monitor
link: #76 #87
> feat: add extra labels and annotations for service monitor

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/templates/deployment.yaml
- charts/apisix/values.yaml
This Pull Request adds some new features for the apisix charts, so that more and more APISIX features can be used.
1. Support to configure ETCD SNI;
2. Support to specify Plugin Attrs;
3. Support to use Pod UID as the APISIX instance id (see https://github.com/apache/apisix/issues/5417 for details).
> feat: support more APISIX features

- charts/apisix/templates/service-admin.yaml
- charts/apisix/templates/service-gateway.yaml
- charts/apisix/templates/servicemonitor.yaml
The `servicemonitor` matches both `apisix-admin` and `apisix-gateway` services, and Prometheus generates two scrape jobs. Adding a `service` label would be more appropriate.
> feat(apisix): add service label

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/templates/deployment.yaml
- charts/apisix/values.yaml
Also, this PR also removes the deprecated `lua_shared_dicts` field in APISIX's config file, now we use the `custom_lua_shared_dict` field.
> feat: add lua module hook support

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
Allow defining the security context on apisix-ingress-controller as we have for apisix-dashboard and apisix.
> feat: allow defining security context on ingress controller helm chart

- charts/apisix-dashboard/README.md
- charts/apisix-ingress-controller/README.md
- charts/apisix/README.md
fix #236 
Unify namespace in README.md and fix some formatting errors.
> docs(README): unify namespace

- charts/apisix-dashboard/templates/ingress.yaml
- charts/apisix/templates/ingress.yaml
Ingress apiVersions `extensions/v1beta1` and `networking.k8s.io/v1beta1` will be deprecated in k8s v1.22. [[source]](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122)
Also fixed `KubeVersion` semverCompare, since `.Capabilities.KubeVersion.GitVersion` is only available in Helm v2 [(source)](https://v2.helm.sh/docs/chart_template_guide/#built-in-objects) and Helm v3 uses `.Capabilities.KubeVersion.Version` [(source)](https://helm.sh/docs/chart_template_guide/builtin_objects/)
> Update ingress to support apiVersion networking.k8s.io/v1

- charts/apisix-dashboard/templates/ingress.yaml
> fix: render the ingressClassName field normally in apisix-dashboard

- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
- fix when custom plugin's attributes is null, type of attributes is object
- make more nginx's configuration configurable in values.yaml
> Fix: when custom plugin's attr is null

- .gitignore
- charts/apisix-ingress-controller/templates/configmap.yaml
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
- charts/apisix/templates/configmap.yaml
- charts/apisix/templates/daemonset.yaml
- charts/apisix/templates/deployment.yaml
- docs/en/latest/apisix-ingress-controller.md
Purpose: Allow `fullnameOverride`s to work correctly to fully automate Helm deployments.
Note: This is an updated PR, a lot less intrusive than the one suggested in https://github.com/apache/apisix-helm-chart/pull/292 (which I have now closed).
- In APISIX admin:
If the etcd subchart is configured to use a `fullnameOverride`, APISIX admin fails to start. This is due to the fact that etcd `fullnameOverride` is not taken into account in APISIX admin's init container nor configmap. This PR is backwards compatible in the sense that if users do not use a `fullnameOverride` for etcd, the chart behaves identically as before.
- In APISIX Ingress Controller:
`apisix.serviceName` and `apisix.serviceNamespace` must be explicitly set, thus not allowing users to fully automate a Helm install when …
> feat: Allow `fullnameOverride`s to work correctly

- charts/apisix-dashboard/templates/ingress.yaml
The property `ingressClassName` should be rendered inside `spec` and not `metadata`
> fix: Move ingressClassName to spec

- charts/apisix-dashboard/templates/configmap.yaml
- charts/apisix-dashboard/values.yaml
There is a wrong spelling in helm chart and yaml config file, where **secret** is misspelled as **secert**. 
This PR fix the misspelling.
> Fix `secret` keyword typo

- charts/apisix/templates/_pod.tpl
- charts/apisix/values.yaml
Since we use the same parameter name as bitnami/etcd charts, this parameter will affect the final configuration of both charts.
This modification makes their behavior consistent.
> fix: apisix-charts's global.imagePullSecrets

- charts/apisix/README.md
- charts/apisix/templates/ingress.yaml
The helm chart supports exposing Apisix Gateway Service through an Ingress.
Unfortunately it does not support choosing `ingressClassName`, so it would work only if there's a default available.
This PR allows setting up a custom Ingress `className` within `values.yaml`, as for example:
```
gateway:
ingress:
enabled: true
className: alb-private
hosts:
- host: api.dev.project.int.corp
paths:
- /
```
Variable name was choosen to be consisting with className used in apisix-dashboard. The change was tested and is backwards compatible.
> Customizable ingressClassName for gateway

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
this pr contains
notes:
- if `wasmPlugins.enabled` is set to `true` and `wasmPlugins.plugins` is empty, `wasm.plugins` will have empty list `[]` as value
- if `wasmPlugins.enabled` is set to `true` and `wasmPlugins.plugins` key is not presented in `values.yaml`, `wasm.plugins` will have `null` as value
- but in production or real world who would enable wasm plugin and not providing any plugin anyway
finally, I welcome all feedbacks and suggestions
> add wasmPlugins options and set wasm plugins to apisix config to apisix chart

- charts/apisix-dashboard/Chart.yaml
I'm opening this PR a second time because last time I made my commit on my forked master branch instead of in a feat branch.
Hello dear APISIX Helm chart maintainers! 
As a apisix user I would like to have the latest changes in the apisix-dashboard helm chart. 
I'm particularly interested in this fix https://github.com/apache/apisix-helm-chart/pull/323 for the ingressClassName field, I took the liberty of just bumping the version of the chart to `0.7.0`
Please let me know if further changes are required to release this chart, I will be happy to contribute!
ps: I believe this project would benefit of having something like helm-docs (https://github.com/norwoodj/helm-docs)
> feat: Bump apisix-dashboard helm chart

- charts/apisix/templates/_helpers.tpl
- charts/apisix/templates/configmap.yaml
Eventhough the `etcd.auth.tls.enabled`, `apisix` tries to connect with `http`.
This PR will solve it.
> fix: use https scheme when etcd.auth.tls.enabled

- charts/apisix/templates/configmap.yaml
Currently, the default value of `etcd.auth.tls.sni` field is `""`, and it'll be set unconditionally to APISIX config.yaml if `etcd.auth.tls.enabled` is `true`, in such a case, an empty SNI will be set when APISIX is trying to access ETCD (in a TLS handshake).
> fix: etcd sni

- charts/apisix/templates/configmap.yaml
- docs/en/latest/apisix.md
> feat: support for using apisix 3.x image

- .github/workflows/ci.yaml
- Makefile
- charts/apisix-dashboard/README.md
- charts/apisix-dashboard/README.md.gotmpl
- charts/apisix-dashboard/values.yaml
- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/README.md.gotmpl
- charts/apisix-ingress-controller/values.yaml
- charts/apisix/README.md
- charts/apisix/README.md.gotmpl
- charts/apisix/values.yaml
Here's a brief description of what I did:
- prefixed the comments in the `values.yaml` file with `--` so that it could be used by the `helm-docs` tool for the description of fields to generate `README.md`.
- added some more comments as description to some yaml fields.
- added `.md.gotmpl` files which will be used to generate the `README.md` files.
- added github action step for checking if helm-docs was run by the user after making changes to the helm chart. This is to ensure that the README.md files are up to date.
- finally, I used the helm-docs tool to regenerate the README.md file.
Closes #334
> chore: use helm docs to generate documentation

- charts/apisix-ingress-controller/templates/configmap.yaml
fix format of configmap for apisix-ingress-controller: https://github.com/apache/apisix-helm-chart/issues/428
before fixed:
```
apiVersion: v1
data:
config.yaml: "# log options\nlog_level: \"info\"\nlog_output: \"stderr\"\ncert_file:
\"/etc/webhook/certs/cert.pem\"\nkey_file: \"/etc/webhook/certs/key.pem\"\nhttp_listen:
\":8080\"\nhttps_listen: \":8443\"\ningress_publish_service: \nenable_profiling:
true\napisix-resource-sync-interval: 300s\nkubernetes:\n  kubeconfig: \"\"\n  resync_interval:
\"6h\"\n  namespace_selector:\n  - \"\"\n  election_id: \"ingress-apisix-leader\"\n
\ ingress_class: \"apisix\"\n  ingress_version: \"networking/v1\"\n  watch_endpointslices:
false\n  apisix_route_version: \"apisix.apache.org/v2\"\n  enable_gateway_api:
false\n  apisix_version: …
```
> fix: fix format of configmap for apisix-ingress-controller

- charts/apisix/Chart.yaml
#448 
0.13 is for APISIX v2.x.
If you are using APISIX v3.x, please use v1.x Helm chart.
> chore: release 0.13.0 for APISIX v2

- charts/apisix/templates/configmap.yaml
Fix broken access logs when log format is set to json, as per issue https://github.com/apache/apisix-helm-chart/issues/452
> fix: apisix access log is corrupted when accessLogFormatEscape is set to json

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/values.yaml
Related to apache/apisix-ingress-controller#1646 and apache/apisix-ingress-controller/pull/1685
> chore: set `apisix-resourcce-sync-interval` defaults to 1h

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
Currently the Helm chart doesn't works on IPv6 single stack as the apisix-ingress-controller will wait until apisix-admin is serving. However, currently it is not possible to set the apisix-admin listen address given 0.0.0.0 is hardcoded and in that way it will never work properly on IPv6 single stack deployments. 
This PR adds the possiblity to set the apisix-admin IP listen address to any value. It should be set to `[::]` when on IPv6 single stack deployments.
> feat: adding IPv6 Single Stack support

- index.yaml
It was deleted in this commit
https://github.com/apache/apisix-helm-chart/commit/8369dbfb86a5ba905f160d6940bafc50afc4ef88
> revert: apisix-dashboard v0.7.1 helm chart

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.schema.json
- charts/apisix/values.yaml
APISIX already has its own list of [default plugins](https://github.com/apache/apisix/blob/809ba09b26ddd62e0efa612f85e90d1aa938ce02/conf/config-default.yaml#L411), and I don't think there's a need to maintain another list of default plugins with helm charts. Only assign `plugins` and `stream_plugins` values to helm if you need to customize the list of enabled plugins.
> chore: clear APISIX plugins and stream_plugins 

- charts/apisix-dashboard/templates/ingress.yaml
- charts/apisix/templates/ingress-admin.yaml
- charts/apisix/templates/ingress.yaml
When the version of the K8S server is lower than 1.14-0, ingress cannot be used because of the indentation problem of this else, which caused the incorrect deletion of an extra line
> fix: ingress support for the lower version k8s server

- charts/apisix/README.md
- charts/apisix/values.yaml
The reason for placing it in extraInitContainers: is to avoid breaking changes.
In addition, users can change or disable it in different scenarios.
> Added an init container to modify system configurations.

- .asf.yaml
- .github/workflows/release.yaml
Due to the refactoring of APISIX Helm chart, we plan to maintain it through the dev branch.
> chore: add release trigger for dev branch

- .asf.yaml
- .github/workflows/release.yaml
Due to the refactoring of APISIX Helm chart, we plan to maintain it through the dev branch.
> chore: add release trigger for dev branch (#558)

- charts/apisix/templates/configmap.yaml
The implementation of admin/view keys using kubernetes secret on #530 doesn't seem to work.
What happens is that on the resulting config.yaml file, the admin key ( and viewer ) will look like:
- name: "admin"
key: "{{APISIX_ADMIN_KEY}}" 
instead of the ' key: ${{APISIX_ADMIN_KEY}} '   that is described on [https://apisix.apache.org/docs/apisix/admin-api/](https://apisix.apache.org/docs/apisix/admin-api/).
The result is that the admin key is literally the value string above and not the value from the env/k8s secret.
-
This PR is the fix on the config map to have the proper key value format to reference the env variable ( filled from the configured secretName secret).
This change was tested, where the admin and viewer keys were correctly set and looked like this on the final config.yaml: …
> fix: config map admin/viewer secret key

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
Some "clients", like AWS Application Load balancer, when forwarding HTTPS requests to upstream servers ( like APISIX ) do not present SNI on the TLS handshake, resulting on APISIX not to be able to fetch the appropriate certificate to establish the connection.
This change is to be able to define and include the "fallback_sni" property on apisix configuration, so that a last resort SNI can be defined and a proper certificate can be retrieved.
> adding fallback_sni to apisix conf

- charts/apisix/templates/pdb.yaml
Why:
* Chart could not be installed in Kubernetes 1.25
* The PodDisruptionBudget used apiVersion that is deprecated before and unavailable in 1.25.
How:
* PodDisruptionBudget apiVersion is updated to match the Kubernetes version. No spec adjustments needed.
* Changes are applied also to k8s versions in which old api versions were deprecated.
Reference:
* https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
I have tested the changes on a 1.25 cluster and reviewed templates visually for older version.
> PDB updated to Kubernetes 1.25

- charts/apisix-ingress-controller/templates/servicemonitor.yaml
Remove the check of `monitoring.coreos.com/v1` API to make it possible to render the ServiceMonitor resource without connection to the target Kubernetes cluster and without supplying `--api-versions` flag for `helm`.
Fixes #330
> fix: render ServiceMonitor regardless of presented CRDs

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
if we configure prometheus plugin with extra labels like bellow
```
pluginAttrs:
prometheus:
metrics:
http_status:
extra_labels:
- request_uri: $uri
- request_method: $request_method
http_latency:
extra_labels:
- request_uri: $uri
- request_method: $request_method
```
then we might run into situation like https://github.com/apache/apisix/issues/7349.
this PR allow user to set the max size of `lua_shared_dict.prometheus-metrics`, incase we'll have more properties in this `meta` field in the future, so I make it as a string type.
> feat: allow customize meta in `nginx_config`

- charts/apisix-dashboard/README.md
- charts/apisix-dashboard/templates/configmap.yaml
- charts/apisix-dashboard/templates/deployment.yaml
- charts/apisix-dashboard/values.yaml
Example values would be:
```yaml
config:
conf:
etcd:
endpoints:
- https://my-cname.domain.com:2379
mtls:
key_file: /etc/etcd/server-client.key
cert_file: /etc/etcd/server-client.crt
ca_file: /etc/etcd/server-ca.crt
existingSecret: cluster-etcd-credentials
```
> feat(dashboard): Allow dashboards to use external etcd with mtls

- charts/apisix/Chart.yaml
- charts/apisix/README.md
- charts/apisix/values.yaml
try install 3.4.1
```shell
helm install apisix charts/apisix \
--set gateway.type=NodePort \
--set ingress-controller.enabled=true \
--namespace ingress-apisix \
--set ingress-controller.config.apisix.serviceNamespace=ingress-apisix
NAME: apisix
LAST DEPLOYED: Wed Jul 26 18:23:45 2023
NAMESPACE: ingress-apisix
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
1. Get the application URL by running these commands:
export NODE_PORT=$(kubectl get --namespace ingress-apisix -o jsonpath="{.spec.ports[0].nodePort}" services apisix-gateway)
export NODE_IP=$(kubectl get nodes --namespace ingress-apisix -o jsonpath="{.items[0].status.addresses[0].address}")
echo http://$NODE_IP:$NODE_PORT
```
```shell
$ kubectl get pod --all-namespaces
NAMESPACE            NAME …
```
> chore: upgrade APISIX to 3.4.1

- charts/apisix/Chart.yaml
- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
https://github.com/apache/apisix/blob/master/CHANGELOG.md#350
> chore: upgrade APISIX to 3.5.0

- charts/apisix/templates/service-gateway.yaml
Closes https://github.com/apache/apisix-helm-chart/issues/588
> Fix: helm validation and install fails when service.type is ClusterIP 

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/values.yaml
Add a note that enabling ServiceMonitor requires Prometheus operator CRDs to be installed.
It's a follow-up on [this comment](https://github.com/apache/apisix-helm-chart/pull/571#issuecomment-1620938165).
Ref: #571
> docs: specify ServiceMonitor requirements in values.yaml

- charts/apisix/README.md
- charts/apisix/templates/deployment.yaml
- charts/apisix/values.yaml
For our use case, we want to deploy our authentication container next to the APISIX so there's minimal latency when using `forward-auth` plugin.
> feat: allow adding extra containers to apisix deployment

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
Depending on the setup, it can be useful to change this value. For example, if using load balancer which already has 60 second timeout, then this timeout should be larger to avoid ungraceful TCP connection closes.
This is the same as `upstream-keepalive-timeout` in ingress nginx controller.
E.g. From AWS [docs][1]:
> We also recommend that you configure the idle timeout of your
application to be larger than the idle timeout configured for the load balancer. Otherwise, if the application closes the TCP connection to the load balancer ungracefully, the load balancer might send a request to the application before it receives the packet indicating that the connection is closed. If this is the case, the server refuses the request from the load balancer and then the load balancer sends an HTTP …
> feat: allow adjusting nginx keepalive timeout

- charts/apisix/README.md
- charts/apisix/templates/ingress.yaml
- charts/apisix/values.yaml
Previously it used `service.http.servicePort` in the Ingress manifest. This made it impossible to forward ingress traffic to TLS port. One option was to disable `http` and change `http.servicePort` to `443`, but then regular HTTP couldn't be used.
This commit allows changing Ingress service port using `ingress.servicePort`. It still falls back to `service.http.servicePort` to keep backward compatibility.
We found this useful to enable encryption between AWS ALB and APISIX. This allowed us to use:
```
alb.ingress.kubernetes.io/backend-protocol: HTTPS
```
> feat: allow changing service port in the Ingress manifest

- charts/apisix/README.md
- charts/apisix/templates/extra-list.yaml
- charts/apisix/values.yaml
The `extraDeploy` option is something that is available in many helm charts (expecially bitnami charts). It is useful for deploying extra resources with the release. E.g. with Apisix you could deploy ApisixGlobalRule.
This commit adds a very simple version of the extraDeploy.
E.g. Using as a string:
```
extraDeploy:
- |
apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
name: global
spec:
plugins:
- name: response-rewrite
enable: true
config:
headers:
remove:
- Server
```
can also use it as a map:
```
- apiVersion: apisix.apache.org/v2
kind: ApisixGlobalRule
metadata:
name: global
spec:
plugins:
- name: response-rewrite
enable: true
config:
headers:
remove:
- Server
```
> feat: allow deploying additional kubernetes resources

- charts/apisix-ingress-controller/crds/ApisixRoute.yaml
The current paths item pattern regex doesn't accept to have wildcards in the middle of the path, meanwhile it's possible to create this Apisix route calling the Apisix API or through Apisix Dashboard.
My currently issue is that I need to match the following URLs:
```
/my/api/country/br/cities
/my/api/country/us/cities
```
But with the current pattern set on the CRD, I'm not able to create the spec.http.match.paths `/my/api/country/*/cities`  through the CRD.
> chore: update ApisixRoute crd paths pattern rule

- charts/apisix-ingress-controller/templates/configmap.yaml
When using the new composite architecture, ingress resources will throw out this error due to the service of the gateway not being set
```
error	ingress/ingress.go:502	failed to get APISIX gateway external IPs	{"error": "service \"\" not found"}
```
This PR set the `ingress_publish_service` to the default gateway service when etcdserver is enabled and the `ingressPublishService` values is empty
> feat: auto populate ingress_publish_service when using etcdserver

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
This was introduced for the chart v1 in [546][1]. This commit introduced the same functionality for the chart v2 as well.
[1]: https://github.com/apache/apisix-helm-chart/pull/546
> feat: add option to control fallback_sni

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/configmap.yaml
- charts/apisix-ingress-controller/values.yaml
It is supposed to be on root level instead of under kubernetes
https://github.com/apache/apisix-ingress-controller/blob/0736bba3f3bda0d47620ef1c6414f73d5b2056e5/pkg/config/config.go#L94
> fix: plugin_metadata_cm path

- charts/apisix/templates/configmap.yaml
Before: we can't generate `etcd` config in config-map.
So we should delete the condition of deployment role.
> fix: delete the condition of deployment role

- charts/apisix/templates/configmap.yaml
Before this PR: apisix-helm-chart will generate the config as follow:
```
`
deployment:
role: data_plane
role_data_plane:
config_provider: etcd
admin:
allow_admin:    # http://nginx.org/en/docs/http/ngx_http_access_module.html#allow
- 127.0.0.1/24
admin_listen:
ip: 0.0.0.0
port: 9180
admin_key:
- name: "admin"
key: edd1c9f034335f136f87ad84b625c8f1
role: admin
- name: "viewer"
key: 4054f7cf07e344346cd3f287985e76a2
role: viewer
etcd:
host:                          # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
- "http://apisix-etcd.default.svc.cluster.local:2379"
prefix: "/apisix"    # configuration prefix in etcd
timeout: 30    # 30 seconds``
```
After this PR:
```
deployment:
role: data_plane
role_data_plane:
config_provider: etcd
etcd:
host: …
```
> improve: don't add admin block if the role is data plane

- charts/apisix-dashboard/README.md
- charts/apisix-dashboard/templates/configmap.yaml
- charts/apisix-dashboard/templates/deployment.yaml
- charts/apisix-dashboard/values.yaml
In more custom apisix deployments with custom plugins being used overriding schema.json and plugins in the configuration are useful features.
- feat: add support for plugins conf
- feat: add support for mounting custom schema.json
- docs: update apisix-dashboard docs
> feat: apisix dashboard custom plugins configuration support

- charts/apisix-ingress-controller/Chart.yaml
- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/values.yaml
Changes since 0.12.2:
* 0c05e7c feat: support configure gateway.tls and adding ingress class (#657)
* 2461821 feat: adding nginx configuration & gateway type in composite architecture  (#644)
* f70b01b fix: plugin_metadata_cm path (#646)
* 2ba669d feat: auto populate ingress_publish_service when using etcdserver (#643)
* c2d4f35 chore: update ApisixRoute crd paths pattern rule (#638)
* a54c769 Enable promethus plugins for service monitoring (#632)
* be31a91 docs: specify ServiceMonitor requirements in values.yaml (#585)
We need the update because of the plugin_metadata_cm fix. Otherwise, we cannot enable datadog metrics.
> chore: bump apisix-ingress-controller to 0.13.0

- index.yaml
It was deleted in this commit
https://github.com/apache/apisix-helm-chart/commit/a1570b28cb0fa702e55b1b128310b7e5282cc083
> revert: apisix v1.10.0 helm chart

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
Allowing to add annotations for Deployment object of `apisix-ingress-controller` makes usage of 3rd party tools like `reloader` possible, e.g.:
```
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
meta.helm.sh/release-name: ingress-apisix
meta.helm.sh/release-namespace: ingress-apisix
reloader.stakater.com/auto: "true"
[...]
```
**Use case**: We are delivering admin key to Kubernetes using `external-secrets-operator` and then passing into apisix via environment variable, and we want ingress controllers to be automatically reloaded when update of secret happens. For this purpose, we need to be able to add `reloader` annotation to the deployment object.
> feat: support adding annotations to Deployment

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
Currently, if `gateway` deployment is enabled, then the `apisix` gateway container in the pod is deployed without any securityContext, and they it is not even configurable. This PR tries to make it configurable.
_Use-case: This is useful, if you want to add_ `NET_BIND_SERVICE` _capability and make_ `apisix` _gateway container listen on privileged port, e.g. 443._
> feat: support securityContext for gateway container

- charts/apisix-ingress-controller/templates/apisix-configmap.yaml
Support for TLS (SSL) configuration was added in this [PR](https://github.com/apache/apisix-helm-chart/pull/657/files), but it seems that indentation of ssl stanza is incorrect, since changing some values does take effect, e.g. changing port from 9443 to 443.
Port is changed in configMap, also in container definition, but internally, `nginx.conf` is still rendered with port 9443. 
According to [this line](https://github.com/apache/apisix/blob/ec77fb8ca2e797aa90d6547a1e323d4f40e27527/apisix/cli/ops.lua#L456), configuration is extracted from YAML file at `apisix.ssl.listen`, not at `ssl.listen`.
If is I manually re-write the configMap and move the section then the port is changed as expected.
> fix: gateway ssl config indentation

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/pdb.yaml
- charts/apisix-ingress-controller/values.yaml
Apisix Helm Chart [allows](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/pdb.yaml) to define `PodDisruptionBudget` policy, but this Helm Chart for `apisix-ingress-controller` does not. This PR adds supports for it.
The code is basically a copy of `PodDisruptionBudget` [template](https://github.com/apache/apisix-helm-chart/blob/master/charts/apisix/templates/pdb.yaml) from mentioned chart, while first if statement is inspired by template of `ingress-nginx` controller's `PodDisruptionBudget` template, if that's OK.
> feat: support PDB in apisix-ingress-controller

- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
Currently, if `gateway` deployment is enabled, then the `apisix` gateway container in the pod is deployed without any resource requests or limits, and they are not even configurable. This PR tries to make them configurable.
> feat: allow to configure gateway.resources

- charts/apisix-ingress-controller/Chart.yaml
- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/values.yaml
The new version of the apisix ingress controller was released - 1.8.0. The released chart is updated with a new image version and a new version of the chart itself.
Includes also:
- https://github.com/apache/apisix-helm-chart/pull/697
- https://github.com/apache/apisix-helm-chart/pull/698
> chore: release ingress 1.8.0 with chart version 0.14.0

- charts/apisix/Chart.yaml
A new version of the apisix chart with
- apisix ingress controller - 0.14.0
- dashboard - 0.8.2
> chore: release apisix v1.11.0

- charts/apisix/README.md
- charts/apisix/templates/_pod.tpl
- charts/apisix/values.yaml
Allowing to add labels for APISIX Pods makes possible the usage of tools like [Istio sidecar injection](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy).
> feat: support adding labels to APISIX Pods

- charts/apisix-ingress-controller/templates/apisix-configmap.yaml
Enable loki-logger plugin for apisix gateway in apisix-ingress-controller Helm Chart.
> feat: enable loki-logger plugin

- charts/apisix/Chart.yaml
- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
change(http2):  https://github.com/apache/apisix/pull/11032
* remove `apisix.ssl.http2.enabled`
* add `apisix.enableHTTP2`
feat(http3): https://github.com/apache/apisix/pull/11010
* add `apisix.ssl.enableHTTP3`
> chore: release APISIX 3.9.1

- charts/apisix/README.md
- charts/apisix/templates/deployment.yaml
- charts/apisix/values.yaml
This PR add topologySpreadContrainsts option for apisix deployment
It was introduced [here](https://github.com/apache/apisix-helm-chart/pull/581/files), but it was removed
> fix: revert Topology Spread Constraints to apisix

- charts/apisix/templates/pdb.yaml
This PR adds a conditional to use the apiVersion according to the kubernetes version being used.
Similar to [this](https://github.com/apache/apisix-helm-chart/blob/97c26c0e802debaf0b5552763e19591a6ac25427/charts/apisix-ingress-controller/templates/pdb.yaml#L18)
It was ok until this [PR](https://github.com/apache/apisix-helm-chart/pull/738/files) deleted the configuration
> fix: revert PDB support to latest kubernetes versions

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
The Lua shared dictionary `prometheus-metrics` is initially configured with a default size of `10m` as specified in the [config-default.yaml](https://github.com/apache/apisix/blob/master/conf/config-default.yaml#L262) file. However, due to the growing number of routes, the dictionary size has been exceeded. Hence, customization of this configuration would prove advantageous.
> feat: Capable of overriding the configurations of the nginx http `lua_shared_dict`

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/templates/deployment.yaml
- charts/apisix/templates/ingress-control.yaml
- charts/apisix/templates/service-control.yaml
- charts/apisix/values.yaml
Retry of #728 due to repeated conflicts...
> feat: Adds Control API releated Resources

- charts/apisix/README.md
- charts/apisix/templates/configmap.yaml
- charts/apisix/values.yaml
This addresses the need from https://github.com/apache/apisix-helm-chart/issues/769
> feat: support setting default http lua_shared_dict

- charts/apisix-ingress-controller/Chart.yaml
- charts/apisix-ingress-controller/crds/apisixic-crds.yaml
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/templates/gatewayproxy.yaml
refactor: update CRD and deployment configurations.
prepare for deploy apisix & apisix-ingress-controller on apisix-standalone mode.
https://github.com/apache/apisix-helm-chart/pull/839
> refactor: update CRD and deployment configurations

- charts/apisix/Chart.yaml
- charts/apisix/README.md
- charts/apisix/values.yaml
fix:  etcd db size  grow without limit when deploy by helm 
https://github.com/apache/apisix/issues/11404
https://github.com/apache/apisix/issues/12377
add autoCompactionRetention  1h ,   autoCompactionMode periodic
> fix: add etcd auto compaction env

- charts/apisix-ingress-controller/Chart.yaml
- charts/apisix-ingress-controller/README.md
- charts/apisix-ingress-controller/templates/deployment.yaml
- charts/apisix-ingress-controller/values.yaml
It should use the default resource configuration of the k8s cluster and allow configuration.
Prevent the application from being unusable due to limit.
> feat: support setting resources for the ingress pod
